#!/bin/sh
#
# This is a wrapper around QEMU that can be used to test the tool. Pass the
# "machinedump" file path as first argument followed by optional command line
# arguments.
#
set -eu

# QEMU machine setup.
MACHINE=q35,accel=kvm,kernel-irqchip=split
CPU=Nehalem,+fsgsbase,+pdpe1gb,+pcid,+invpcid,+xsave,+xsaves,+xsaveopt,+vmx,+vme
RAM=4G

# Parse the command line.
if [ $# -lt 1 ]; then
    echo "Usage: $(basename "$0") <kernel> [args]" >&2
    exit 1
fi
kernel="$1"
shift

# Create a temporary directory.
TMPDIR="$(mktemp -d)"
trap "rm -rf -- '$TMPDIR'" EXIT

# A subdirectory for the ISO files.
ISODIR="$TMPDIR"/iso
mkdir -p "$ISODIR"

# Copy the kernel file.
cp "$kernel" "$ISODIR"/kernel

# Create the grub configuration file.
mkdir -p "$ISODIR"/boot/grub
cat > "$ISODIR"/boot/grub/grub.cfg <<-EOF
set default=0
set timeout=0

serial --unit=0 --speed=115200
terminal_input serial
terminal_output serial

menuentry 'Boot' {
  multiboot2 /kernel $*
}
EOF

# Build a bootable grub ISO kernel.
grub-mkrescue -o "$TMPDIR"/grub.iso "$ISODIR"

# Run qemu.
set -x
qemu-system-x86_64                      \
        -machine "$MACHINE"             \
        -cpu "$CPU"                     \
        -m "$RAM"                       \
        -display none                   \
        -serial mon:stdio               \
        -device intel-iommu             \
        -cdrom "$TMPDIR"/grub.iso
